version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.12.0
     steps:
       - checkout
       - run: npm install
       - run: npm audit fix
       - run: npx gulp build
       - run: node .circleci/deploy.js
       - run: echo "Site has been deployed"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master